//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagementSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerSetup
    {
        public int customerId { get; set; }
        public string cName { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string cMunicipality { get; set; }
        public Nullable<int> cWard { get; set; }
        public string cContact { get; set; }
        public string cEmail { get; set; }
        public string cWeb { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<int> deletedBy { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
    }
}
