//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagementSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendorSetup
    {
        public int VendorId { get; set; }
        public string VName { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string VMunicipality { get; set; }
        public Nullable<int> VWard { get; set; }
        public string VContact { get; set; }
        public string VEmail { get; set; }
        public string VWeb { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<int> deletedBy { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
    }
}
